PhotoFrame.Web/Controllers/MagicMirrorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoFrame.Web.Models;

using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PhotoFrame.Web.ViewModel;

namespace PhotoFrame.Web.Controllers
{
    public class MagicMirrorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> manager;

        public MagicMirrorController()
        {
            db = new ApplicationDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }
        // GET: MagicMirror
        public ActionResult Index()
        {
            return View(db.Photos.ToList());
        }
        public async Task<ActionResult> GetNextPhoto(int? currentPhotoId)
        {
            if (ViewBag.PhotoCount==null || ViewBag.PhotoCount < 0) ViewBag.PhotoCount = 0;

            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            List<Photo> photos = currentUser.Photos.ToList<Photo>();
            int nextPhoto = GetRandomNumber(photos.Count);
            ViewBag.CurrentPhotoId = photos[nextPhoto].Id;
            ViewBag.PhotoCount += 1;
            return View(photos[nextPhoto]);
        }
        private int GetRandomNumber(int maxValue)
        {
            Random r = new Random();
            int nextNum = r.Next(0, maxValue);
            return nextNum;
        }
        // GET: MagicMirror/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Photo photo = db.Photos.Find(id);
        //    if (photo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(photo);
        //}

        //// GET: MagicMirror/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: MagicMirror/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,FileName,FriendlyName,UploadDate,Bytes,MimeType,FileExtension")] Photo photo)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Photos.Add(photo);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(photo);
        //}

        //// GET: MagicMirror/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Photo photo = db.Photos.Find(id);
        //    if (photo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(photo);
        //}

        //// POST: MagicMirror/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,FileName,FriendlyName,UploadDate,Bytes,MimeType,FileExtension")] Photo photo)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(photo).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(photo);
        //}

        //// GET: MagicMirror/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Photo photo = db.Photos.Find(id);
        //    if (photo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(photo);
        //}

        //// POST: MagicMirror/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Photo photo = db.Photos.Find(id);
        //    db.Photos.Remove(photo);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoFrame.Web/Views/MagicMirror/Create.cshtml
@model PhotoFrame.Web.Models.Photo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FriendlyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FriendlyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UploadDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UploadDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UploadDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bytes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bytes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileExtension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileExtension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileExtension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoFrame.Web/Views/MagicMirror/Delete.cshtml
@model PhotoFrame.Web.Models.Photo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FriendlyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bytes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileExtension)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhotoFrame.Web/Views/MagicMirror/Details.cshtml
@model PhotoFrame.Web.Models.Photo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FriendlyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bytes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileExtension)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhotoFrame.Web/Views/MagicMirror/Edit.cshtml
@model PhotoFrame.Web.Models.Photo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FriendlyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FriendlyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UploadDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UploadDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UploadDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bytes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bytes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileExtension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileExtension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileExtension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoFrame.Web/Views/MagicMirror/GetNextPhoto.cshtml
@model PhotoFrame.Web.Models.Photo

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetNextPhoto</title>
</head>
<body>
    <div>
        <h4>Photo</h4>
        <hr />
        <div>@Html.ActionLink("Get Next Photo", "GetNextPhoto", "MagicMirror")</div>
        <div class="containerCentered">
            <img src="~/File?id=@Model.Id" alt="avatar" class="maxImage" />
        </div>
    </div>
    @*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@
</body>
</html>

PhotoFrame.Web/Views/MagicMirror/Index.cshtml
@model IEnumerable<PhotoFrame.Web.Models.Photo>

@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UploadDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bytes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MimeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileExtension)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FriendlyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UploadDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bytes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MimeType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileExtension)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>