PhotoFrame.Web/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoFrame.Web.Controllers
{
    public class LinksController : Controller
    {
        // GET: Links
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Privacy()
        {
            return View();
        }
        public ActionResult Legal()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View();
        }
        public ActionResult Careers()
        {
            return View();
        }
        public ActionResult LoginHelp()
        {
            return View();
        }
    }
}

PhotoFrame.Web/Views/Shared/_Brand.cshtml
<div class="containerCentered">
    <p>
        <img src="~/Content/Images/PFLogo.gif" />
        <img src="~/Content/Images/PFBrand.gif" />
    </p>
</div>

PhotoFrame.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Photo Frame by LeapLily</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @using Microsoft.AspNet.Identity
    @if (Request.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @*<a href="@Url.Action("Index","Home")" class="navbar-brand">
                            <img src="@Url.Content("~/Content/Images/PhotoFrameLogo.png")" />
                        </a>*@
                </div>
                <div class="navbar-collapse collapse">
                    @*<ul class="nav navbar-nav navbar-brand">*@
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @*</ul>*@
                    
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    }
    <div class="container body-content pfSiteBackground">
        @RenderBody()
        <hr class="footerHr" />
        <div class="footerMain">
            <footer class="footerRight">
                <div class="containerCentered">
                    <ul>
                        <li class="footerCopyright">&copy; @DateTime.Now.Year - Photo Frame Inc.</li>
                        <li>
                            @Html.ActionLink("Privacy", "Privacy", "Links")
                        </li>
                        <li>
                            @Html.ActionLink("Legal", "Legal", "Links")
                        </li>
                        <li>
                            @Html.ActionLink("Contact Us", "ContactUs", "Links")
                        </li>
                        <li>
                            @Html.ActionLink("Careers", "Careers", "Links")
                        </li>
                    </ul>

                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datetime")
    @RenderSection("scripts", required: false)

</body>
</html>